/** The Weird Web October 2026 prompts. One component per day, as they ship. */
export const DAYS: { day: number; theme: string; component?: string; href?: string }[] = [
  { day: 1, theme: "Reveal", component: "Scratchcard", href: "/weird/scratchcard" },
  { day: 2, theme: "Spark" },
  { day: 3, theme: "Fake" },
  { day: 4, theme: "Plastic" },
  { day: 5, theme: "Sheet" },
  { day: 6, theme: "Analog" },
  { day: 7, theme: "Organic" },
  { day: 8, theme: "Skeumorphism" },
  { day: 9, theme: "Spicy" },
  { day: 10, theme: "Layers" },
  { day: 11, theme: "Stuck" },
  { day: 12, theme: "Pointy" },
  { day: 13, theme: "Scratch" },
  { day: 14, theme: "Origami" },
  { day: 15, theme: "Wooden" },
  { day: 16, theme: "Instant" },
  { day: 17, theme: "Branching" },
  { day: 18, theme: "Geometric" },
  { day: 19, theme: "Distorted" },
  { day: 20, theme: "Undefined" },
  { day: 21, theme: "Illusion" },
  { day: 22, theme: "Skeletons" },
  { day: 23, theme: "Incognito" },
  { day: 24, theme: "Collage" },
  { day: 25, theme: "Ascending" },
  { day: 26, theme: "Net" },
  { day: 27, theme: "Spiral" },
  { day: 28, theme: "Smooth" },
  { day: 29, theme: "The End" },
  { day: 30, theme: "Pastel" },
  { day: 31, theme: "Spooky" },
];

export const pad = (n: number) => String(n).padStart(2, "0");
